--  -- shared opts
--  local capabilities = vim.lsp.protocol.make_client_capabilities()
--  local on_attach = function(client, bufnr)
--    client.server_capabilities.semanticTokensProvider = nil
--  end
--
--  capabilities.textDocument.completion.completionItem = {
--    documentationFormat = { "markdown", "plaintext" },
--    snippetSupport = true,
--    preselectSupport = true,
--    insertReplaceSupport = true,
--    labelDetailsSupport = true,
--    deprecatedSupport = true,
--    commitCharactersSupport = true,
--    tagSupport = { valueSet = { 1 } },
--    resolveSupport = {
--      properties = { "documentation", "detail", "additionalTextEdits" },
--    },
--  }
--
--  -- helper to define+enable
--  local function lsp_enable(name, opts)
--    vim.lsp.config(name, opts or {})
--    vim.lsp.enable(name)
--  end
--
--  -- bulk servers
--  local servers = {
--    "angularls",
--    "awk_ls",
--    "bashls",
--    "cmake",
--    "cssls",
--    "dartls",
--    "dockerls",
--    "gopls",
--    "graphql",
--    "groovyls",
--    "html",
--    "jdtls",
--    "ts_ls",
--    "jsonls",
--    "kotlin_language_server",
--    "texlab",
--    "marksman",
--    "pyright",
--    "rust_analyzer",
--    "sqlls",
--    "lemminx",
--    -- "lua_ls",  -- custom below
--    -- "yamlls",  -- custom below
--    -- "clangd",  -- custom below
--    -- "arduino_language_server", -- custom below
--  }
--
--  for _, name in ipairs(servers) do
--    lsp_enable(name, {
--      on_attach = on_attach,
--      capabilities = capabilities,
--    })
--  end
--
--   Arduino
--  lsp_enable("arduino_language_server", {
--    on_attach = on_attach,
--    capabilities = capabilities,
--    cmd = {
--      "arduino-language-server",
--      "-clangd", "/Users/attict/.local/share/nvim/mason/bin/clangd",
--      "-cli", "/opt/homebrew/bin/arduino-cli",
--      "-cli-config", "/Users/attict/Library/Arduino15/arduino-cli.yaml",
--      "-fqbn", "arduino:avr:mega",
--    },
--  })
--
--   Clangd
--  lsp_enable("clangd", {
--    on_attach = on_attach,
--    cmd = {
--      "clangd",
--      "--background-index",
--      "--suggest-missing-includes",
--      -- "--offset-encoding=utf-16",
--    },
--    filetypes = { "c", "cpp", "objc", "objcpp", "metal", "hlsl" },
--  })
--
--  -- SourceKit (Swift/Obj-C)
--  lsp_enable("sourcekit", {
--    on_attach = on_attach,
--    capabilities = capabilities,
--    settings = {
--      sourcekit = {
--        sdkPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk",
--        targetArch = "x86_64-apple-ios16.4-simulator",
--      },
--    },
--  })
--
--  -- Lua
--  lsp_enable("lua_ls", {
--    on_attach = on_attach,
--    capabilities = capabilities,
--    settings = {
--      Lua = { diagnostics = { globals = { "vim", "on_attach" } } },
--    },
--  })
--
--  -- YAML
--  lsp_enable("yamlls", {
--    on_attach = on_attach,
--    capabilities = capabilities,
--    settings = { yaml = { keyOrdering = false } },
--  })


--  -- Capabilities / on_attach stay the same
--  local capabilities = vim.lsp.protocol.make_client_capabilities()
--  local on_attach = function(client, bufnr)
--    client.server_capabilities.semanticTokensProvider = nil
--  end
--
--  capabilities.textDocument.completion.completionItem = {
--    documentationFormat = { "markdown", "plaintext" },
--    snippetSupport = true,
--    preselectSupport = true,
--    insertReplaceSupport = true,
--    labelDetailsSupport = true,
--    deprecatedSupport = true,
--    commitCharactersSupport = true,
--    tagSupport = { valueSet = { 1 } },
--    resolveSupport = {
--      properties = { "documentation", "detail", "additionalTextEdits" },
--    },
--  }
--
--  -- Use core API (fallback to lspconfig if you ever open on 0.10)
--  local lsp = (vim.lsp and vim.lsp.config) or require("lspconfig")
--
--  local servers = {
--    "angularls", -- Angular
--    --"arduino_language_server", -- Arduino
--    "awk_ls", -- AWK
--    "bashls", -- BASH
--    --"clangd", -- C, CPP
--    "cmake", -- CMake
--    "cssls", -- CSS
--    --"omnisharp_mono", -- C#
--    "dartls",
--    "dockerls", -- Docker
--    "gopls", -- GO
--    "graphql", -- GraphQL
--    "groovyls", -- Groovy
--    "html", -- HTML
--    "jdtls", -- Java
--    "ts_ls", -- JavaScript, TypeScript
--    "jsonls", -- JSON
--    "kotlin_language_server", -- Kotlin
--    "texlab", -- LaTeX
--    --"lua_ls", -- LUA
--    "marksman", -- Markdown
--    "pyright", -- Python
--    "rust_analyzer", -- Rust
--    "sqlls", -- SQL
--    "lemminx", -- XML
--    --"yamlls" -- YAML
--  }
--
--  for _, server in ipairs(servers) do
--    if lsp[server] then
--      lsp[server].setup {
--        on_attach = on_attach,
--        capabilities = capabilities,
--      }
--    end
--  end
--
--  -- Arduino (custom cmd)
--  if lsp.arduino_language_server then
--    lsp.arduino_language_server.setup {
--      on_attach = on_attach,
--      capabilities = capabilities,
--      cmd = {
--        "arduino-language-server",
--        "-clangd", "/Users/attict/.local/share/nvim/mason/bin/clangd",
--        "-cli", "/opt/homebrew/bin/arduino-cli",
--        "-cli-config", "/Users/attict/Library/Arduino15/arduino-cli.yaml",
--        "-fqbn", "arduino:avr:mega",
--      },
--    }
--  end
--
--  -- Clangd (custom flags + filetypes)
--  if lsp.clangd then
--    lsp.clangd.setup {
--      on_attach = on_attach,
--      cmd = {
--        "clangd",
--        "--background-index",
--        "--suggest-missing-includes",
--        -- "--offset-encoding=utf-16",
--      },
--      filetypes = { "c", "cpp", "objc", "objcpp", "metal", "hlsl" },
--    }
--  end
--
--  -- SourceKit (Swift/Obj-C)
--  if lsp.sourcekit then
--    lsp.sourcekit.setup {
--      on_attach = on_attach,
--      capabilities = capabilities,
--      settings = {
--        sourcekit = {
--          sdkPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk",
--          targetArch = "x86_64-apple-ios16.4-simulator",
--        },
--      },
--    }
--  end
--
--  -- Lua
--  if lsp.lua_ls then
--    lsp.lua_ls.setup {
--      on_attach = on_attach,
--      capabilities = capabilities,
--      settings = {
--        Lua = {
--          diagnostics = { globals = { "vim", "on_attach" } },
--        },
--      },
--    }
--  end
--
--  -- YAML
--  if lsp.yamlls then
--    lsp.yamlls.setup {
--      on_attach = on_attach,
--      capabilities = capabilities,
--      settings = {
--        yaml = { keyOrdering = false },
--      },
--    }
--  end




--   local capabilities = vim.lsp.protocol.make_client_capabilities()
--   local lspconfig = require('lspconfig')
--   local on_attach = function(client, bufnr)
--       client.server_capabilities.semanticTokensProvider = nil
--   end
--
--   capabilities.textDocument.completion.completionItem = {
--     documentationFormat = { "markdown", "plaintext" },
--     snippetSupport = true,
--     preselectSupport = true,
--     insertReplaceSupport = true,
--     labelDetailsSupport = true,
--     deprecatedSupport = true,
--     commitCharactersSupport = true,
--     tagSupport = { valueSet = { 1 } },
--     resolveSupport = {
--       properties = {
--         "documentation",
--         "detail",
--         "additionalTextEdits",
--       },
--     },
--   }
--
--
--   local servers = {
--     "angularls", -- Angular
--     --"arduino_language_server", -- Arduino
--     "awk_ls", -- AWK
--     "bashls", -- BASH
--     --"clangd", -- C, CPP
--     "cmake", -- CMake
--     "cssls", -- CSS
--     --"omnisharp_mono", -- C#
--     "dartls",
--     "dockerls", -- Docker
--     "gopls", -- GO
--     "graphql", -- GraphQL
--     "groovyls", -- Groovy
--     "html", -- HTML
--     "jdtls", -- Java
--     "ts_ls", -- JavaScript, TypeScript
--     "jsonls", -- JSON
--     "kotlin_language_server", -- Kotlin
--     "texlab", -- LaTeX
--     --"lua_ls", -- LUA
--     "marksman", --Markdown
--     "pyright", -- Python
--     "rust_analyzer", -- Rust
--     "sqlls", -- SQL
--     "lemminx", -- XML
--     --"yamlls" -- YAML
--   }
--
--   for _, lsp in ipairs(servers) do
--     require("lspconfig")[lsp].setup {
--       on_attach = on_attach,
--       capabilities = capabilities,
--     }
--   end
--
--   require("lspconfig")["arduino_language_server"].setup {
--     on_attach = on_attach,
--     capabilities = capabilities,
--     cmd = {
--       "arduino-language-server",
--       "-clangd", "/Users/attict/.local/share/nvim/mason/bin/clangd",
--       "-cli", "/opt/homebrew/bin/arduino-cli",
--       "-cli-config", "/Users/attict/Library/Arduino15/arduino-cli.yaml",
--       "-fqbn", "arduino:avr:mega"
--     },
--     --settings = {
--     --  arduino_language_server = {
--     --    cli_config = "/Users/attict/Documents/learning/arduino/00_MyFirstSketch/sketch.yaml",
--     --  },
--     --  --cli_config = "/Users/attict/Library/Arduino15/arduino-cli.yaml",
--     --  --arduino_language_server = {
--     --  --  cli_config = "/Users/attict/Library/Arduino15/arduino-cli.yaml",
--     --  --},
--     --},
--   }
--
--   require("lspconfig")["clangd"].setup {
--     on_attach = on_attach,
--     cmd = {
--       "clangd",
--       "--background-index",
--       "--suggest-missing-includes",
--       --"--offset-encoding=utf-16",
--       --'--query-driver="/usr/local/opt/gcc-arm-none-eabi-8-2019-q3-update/bin/arm-none-eabi-gcc"'
--     },
--     filetypes = {"c", "cpp", "objc", "objcpp", "metal", "hlsl"},
--   }
--
--   -- SourceKit: Apple / Swift / Obj-C
--   require("lspconfig").sourcekit.setup {
--     on_attach = on_attach,
--     capabilities = capabilities,
--     settings = {
--       sourcekit = {
--         sdkPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk",
--         targetArch = "x86_64-apple-ios16.4-simulator",
--       },
--     },
--   }
--
--   require("lspconfig")["lua_ls"].setup {
--     on_attach = on_attach,
--     capabilities = capabilities,
--     settings = {
--       Lua = {
--         diagnostics = {
--           globals = { "vim", "on_attach" },
--         },
--       }
--     }
--   }
--
--   lspconfig.yamlls.setup {
--     on_attach = on_attach,
--     capabilities = capabilities,
--     settings = {
--       yaml = {
--         keyOrdering = false
--       }
--     }
--   }
--
