local options = {
  ensure_installed = {
    "arduino",
    "awk",
    "bash",
    "c",
    "cmake",
    "cpp",
    "comment", -- Tags like TODO, FIXME
    "css",
    "c_sharp",
    "dart",
    "dockerfile",
    "glsl",
    "go",
    "graphql",
    "hlsl",
    "html",
    "ini",
    "java",
    "javascript",
    "json",
    "kotlin",
    "llvm",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "php",
    "python",
    "regex",
    "rust",
    "scss",
    "sql",
    "swift",
    "typescript",
    "vim",
    "yaml",
  },
  highlight = {
    enable = true,
    use_languagetree = true,
  },
  indent = {
    enable = true,
  },
}

require("nvim-treesitter.configs").setup(options)
